#!/usr/bin/env python3
"""
Compare unified-schema apply output vs migration-chain apply output for P0 tables.

Inputs are schema JSON files generated by `scripts/db/extract_schema.py`.
The gate focuses on exact column-name and secondary-index signatures for a fixed
set of P0 tables so drift becomes a hard blocker in CI.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


P0_TABLES = [
    "room_memberships",
    "events",
    "account_data",
    "room_account_data",
    "push_rules",
    "room_retention_policies",
    "device_verification_request",
    "search_index",
]


@dataclass(frozen=True)
class AlignmentFailure:
    table: str
    category: str
    expected: list[str]
    actual: list[str]


def load_schema(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def normalize_columns(table: dict[str, Any]) -> list[str]:
    return sorted(column["name"] for column in table.get("columns", []))


def normalize_indexes(table: dict[str, Any]) -> list[str]:
    signatures = []
    for index in table.get("indexes", []):
        if index.get("is_primary"):
            continue
        columns = ",".join(index.get("columns", []))
        uniqueness = "unique" if index.get("is_unique") else "nonunique"
        signatures.append(f"{index['name']}[{uniqueness}]({columns})")
    return sorted(signatures)


def compare_p0_tables(
    expected_schema: dict[str, Any], actual_schema: dict[str, Any]
) -> list[AlignmentFailure]:
    failures: list[AlignmentFailure] = []
    expected_tables = expected_schema.get("tables", {})
    actual_tables = actual_schema.get("tables", {})

    for table_name in P0_TABLES:
        expected_table = expected_tables.get(table_name)
        actual_table = actual_tables.get(table_name)

        if expected_table is None or actual_table is None:
            failures.append(
                AlignmentFailure(
                    table=table_name,
                    category="missing_table",
                    expected=["present" if expected_table is not None else "missing"],
                    actual=["present" if actual_table is not None else "missing"],
                )
            )
            continue

        expected_columns = normalize_columns(expected_table)
        actual_columns = normalize_columns(actual_table)
        if expected_columns != actual_columns:
            failures.append(
                AlignmentFailure(
                    table=table_name,
                    category="column_set",
                    expected=expected_columns,
                    actual=actual_columns,
                )
            )

        expected_indexes = normalize_indexes(expected_table)
        actual_indexes = normalize_indexes(actual_table)
        if expected_indexes != actual_indexes:
            failures.append(
                AlignmentFailure(
                    table=table_name,
                    category="index_set",
                    expected=expected_indexes,
                    actual=actual_indexes,
                )
            )

    return failures


def render_text_report(
    failures: list[AlignmentFailure], expected_label: str, actual_label: str
) -> str:
    lines = [
        "P0 Unified-vs-Migrations Schema Alignment",
        "=" * 80,
        f"Expected: {expected_label}",
        f"Actual:   {actual_label}",
        f"P0 tables checked: {len(P0_TABLES)}",
        "",
    ]

    if not failures:
        lines.append("PASS: all P0 tables match for column and secondary-index sets.")
        return "\n".join(lines) + "\n"

    lines.append(f"FAIL: detected {len(failures)} alignment mismatches.")
    lines.append("")
    for failure in failures:
        lines.append(f"- [{failure.category}] {failure.table}")
        lines.append(f"  expected: {', '.join(failure.expected) if failure.expected else '(empty)'}")
        lines.append(f"  actual:   {', '.join(failure.actual) if failure.actual else '(empty)'}")
        lines.append("")
    return "\n".join(lines)


def render_markdown_report(
    failures: list[AlignmentFailure], expected_label: str, actual_label: str
) -> str:
    lines = [
        "# P0 Unified-vs-Migrations Schema Alignment",
        "",
        f"- Expected: `{expected_label}`",
        f"- Actual: `{actual_label}`",
        f"- P0 tables checked: `{len(P0_TABLES)}`",
        "",
    ]

    if not failures:
        lines.append("- Status: PASS")
        lines.append("- Result: all P0 tables match for column and secondary-index sets.")
        lines.append("")
        return "\n".join(lines)

    lines.append(f"- Status: FAIL ({len(failures)} mismatches)")
    lines.append("")
    for failure in failures:
        lines.append(f"## {failure.table} / {failure.category}")
        lines.append("")
        lines.append("**Expected**")
        lines.append("")
        if failure.expected:
            for item in failure.expected:
                lines.append(f"- `{item}`")
        else:
            lines.append("- `(empty)`")
        lines.append("")
        lines.append("**Actual**")
        lines.append("")
        if failure.actual:
            for item in failure.actual:
                lines.append(f"- `{item}`")
        else:
            lines.append("- `(empty)`")
        lines.append("")
    return "\n".join(lines)


def write_report(path: str | None, content: str) -> None:
    if not path:
        return
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Compare unified schema apply vs sqlx migration apply for P0 tables"
    )
    parser.add_argument("expected", help="Schema JSON extracted from unified schema apply")
    parser.add_argument("actual", help="Schema JSON extracted from migration-chain apply")
    parser.add_argument("--text-report", help="Write text report to this path")
    parser.add_argument("--markdown-report", help="Write markdown report to this path")
    args = parser.parse_args()

    expected_path = Path(args.expected)
    actual_path = Path(args.actual)

    expected_schema = load_schema(expected_path)
    actual_schema = load_schema(actual_path)
    failures = compare_p0_tables(expected_schema, actual_schema)

    text_report = render_text_report(failures, str(expected_path), str(actual_path))
    markdown_report = render_markdown_report(failures, str(expected_path), str(actual_path))

    write_report(args.text_report, text_report)
    write_report(args.markdown_report, markdown_report)

    sys.stdout.write(text_report)
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
