-- =====================================================================
-- Undo Migration: 20260906000000_normalize_room_alias_server_name.undo.sql
--
-- Forward 迁移: 将 room_aliases.server_name 及 room_alias 中 ':' 之后的部分
--               转为小写（Matrix spec v1.11 §4.3：server_name 大小写不敏感）。
--
-- 回滚: **无法自动回滚（数据有损）**。
--
-- 原因: forward 迁移执行的是
--   room_alias  = SUBSTRING(room_alias FROM 1 FOR POSITION(':' IN room_alias))
--                 || LOWER(SUBSTRING(room_alias FROM POSITION(':' IN room_alias) + 1))
--   server_name = LOWER(server_name)
-- 原始大小写信息在 LOWER() 之后**不复存在**，没有备份就无法还原。
-- 试图"反向大写化"（例如 INITCAP）只会制造错误数据，因此本 undo 不做任何改写。
--
-- 需要回滚时的正确做法:
--   1. 从执行 forward 迁移之前的数据库备份还原 room_aliases；或
--   2. 接受小写化结果 —— 它与 Matrix spec 一致，且
--      RoomAlias::new / set_room_alias / get_room_by_alias 的写入路径本就小写化
--      server_name，因此新数据不会与旧数据冲突。
--
-- 另注: forward 迁移是幂等的（仅处理 server_name <> LOWER(server_name) 的行，
-- 且跳过无 ':' 边界的空 server_name），重复执行无害。
-- =====================================================================

-- 有意为空：见上方说明。
