#!/usr/bin/env bash
# Regenerate the SDK-lane ledger fixtures consumed by matrix-js-sdk's
# `scripts/contract-sync.mjs` (whose DEFAULT_INGEST_SOURCE_DIR is this directory).
#
# TWO LANES — do not conflate them:
#   tests/unit/fixtures/ledger_export/       golden fixtures for
#       tests/unit/ledger_export_tests.rs. Those tests are
#       `#[cfg(not(any(feature = "all-extensions", ...opt-in extensions)))]`,
#       so this lane MUST be generated by a DEFAULT-feature build, and it
#       carries the fixed --timestamp/--commit declared in that test file.
#   tests/unit/fixtures/ledger_export_sdk/   THIS lane. The SDK ingests the
#       `all-extensions` compile, so this lane MUST be generated with
#       `--features all-extensions`.
# Same file names, different feature sets -> different entry counts
# (default-feature `all` = 1320; all-extensions `all` = 1407). Conflating the
# two is what made the SDK mirror look "87 routes ahead" of the backend.
#
# The defaults below use the SAME fixed timestamp/commit as the golden fixtures
# so a regeneration is byte-stable and reviewable as a diff. Export
# TIMESTAMP/COMMIT to override (e.g. to mirror a specific CI artifact).
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_DIR="${ROOT_DIR}/tests/unit/fixtures/ledger_export_sdk"
TIMESTAMP="${TIMESTAMP:-2026-05-02T00:00:00Z}"
COMMIT="${COMMIT:-0000000000000000000000000000000000000000}"

mkdir -p "${OUTPUT_DIR}"

for profile in default worker all; do
    cargo run --features all-extensions --bin synapse_ledger_export -- \
        --profile="${profile}" \
        --timestamp="${TIMESTAMP}" \
        --commit="${COMMIT}" \
        --output="${OUTPUT_DIR}/${profile}.json"
done

printf 'sdk ledger fixtures written to %s\n' "${OUTPUT_DIR}"
