#!/bin/bash
# 快速生成所有必需的环境变量密钥

echo "# Synapse-Rust 环境变量"
echo "# 生成时间: $(date)"
echo ""
echo "# ===== 必需变量 ====="
echo "OLM_PICKLE_KEY=$(openssl rand -hex 32)"
echo "SYNAPSE_DB_PASSWORD=$(openssl rand -base64 24)"
echo "SYNAPSE_JWT_SECRET=$(openssl rand -base64 32)"
echo "SYNAPSE_MACAROON_SECRET=$(openssl rand -base64 32)"
echo "SYNAPSE_FORM_SECRET=$(openssl rand -base64 32)"
echo "SYNAPSE_REGISTRATION_SECRET=$(openssl rand -base64 32)"
echo "SYNAPSE_SECURITY_SECRET=$(openssl rand -base64 32)"
echo ""
echo "# ===== 服务器配置 ====="
echo "SERVER_NAME=localhost"
echo "PUBLIC_BASEURL=http://localhost:8008"
echo ""
echo "# ===== 数据库配置 ====="
echo "DATABASE_URL=postgresql://synapse:synapse@localhost:5432/synapse"
echo ""
echo "# ===== Redis 配置 ====="
echo "REDIS_URL=redis://localhost:6379"
