#!/bin/bash

# Synapse Rust - Federation Signature Authentication Integration Test Script
# 测试联邦签名认证功能

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}================================${NC}"
echo -e "${BLUE}  Federation签名认证集成测试${NC}"
echo -e "${BLUE}================================${NC}"
echo ""

# Configuration
SERVER_URL="http://localhost:8008"
ORIGIN="example.com"
DESTINATION="cjystx.top"

# Test results
TOTAL_TESTS=0
PASSED_TESTS=0
FAILED_TESTS=0

# Function to run a test
run_test() {
    local test_name="$1"
    local test_command="$2"
    local expected_result="$3"  # "success" or "failure"

    TOTAL_TESTS=$((TOTAL_TESTS + 1))

    echo -e "${YELLOW}测试 $TOTAL_TESTS: $test_name${NC}"

    if eval "$test_command" > /dev/null 2>&1; then
        if [ "$expected_result" == "success" ]; then
            echo -e "${GREEN}✓ 通过${NC}"
            PASSED_TESTS=$((PASSED_TESTS + 1))
        else
            echo -e "${RED}✗ 失败 - 预期失败但成功了${NC}"
            FAILED_TESTS=$((FAILED_TESTS + 1))
        fi
    else
        if [ "$expected_result" == "failure" ]; then
            echo -e "${GREEN}✓ 通过 - 预期失败${NC}"
            PASSED_TESTS=$((PASSED_TESTS + 1))
        else
            echo -e "${RED}✗ 失败${NC}"
            FAILED_TESTS=$((FAILED_TESTS + 1))
        fi
    fi
    echo ""
}

# Generate test keypair using Rust
echo -e "${YELLOW}生成测试密钥对...${NC}"
KEYPAIR_OUTPUT=$(cd /home/hula/synapse_rust && cargo run --bin generate_test_keypair 2>/dev/null || echo "Using manual key generation")

# Manual key generation for testing
# In production, these would be generated by the Rust binary
# For this test, we'll use a known test key
SECRET_KEY="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
PUBLIC_KEY="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB="

echo -e "${GREEN}测试密钥生成成功${NC}"
echo ""

echo -e "${BLUE}1. 测试公共Federation端点（无需认证）${NC}"
echo ""

# Test 1: Federation Version (public endpoint)
run_test "Federation Version API" \
    "curl -s $SERVER_URL/_matrix/federation/v1/version | grep -q 'version'" \
    "success"

# Test 2: Federation Discovery (public endpoint)
run_test "Federation Discovery API" \
    "curl -s $SERVER_URL/_matrix/federation/v1 | grep -q 'server_name'" \
    "success"

# Test 3: Server Key (public endpoint)
run_test "Server Key API" \
    "curl -s $SERVER_URL/_matrix/federation/v2/server | grep -q 'verify_keys'" \
    "success"

# Test 4: Key Query (public endpoint)
run_test "Key Query API" \
    "curl -s $SERVER_URL/_matrix/federation/v2/query/$DESTINATION/ed25519:1 | grep -q 'verify_keys'" \
    "success"

echo -e "${BLUE}2. 测试受保护的Federation端点（需要认证）${NC}"
echo ""

# Test 5: Room Members without signature (should fail)
run_test "Room Members (no signature - should fail)" \
    "curl -s $SERVER_URL/_matrix/federation/v1/members/test_room | grep -q 'M_UNAUTHORIZED'" \
    "success"

# Test 6: User Devices without signature (should fail)
run_test "User Devices (no signature - should fail)" \
    "curl -s $SERVER_URL/_matrix/federation/v1/user/devices/@test:example.com | grep -q 'M_UNAUTHORIZED'" \
    "success"

# Test 7: Send Transaction without signature (should fail)
run_test "Send Transaction (no signature - should fail)" \
    "curl -s -X PUT $SERVER_URL/_matrix/federation/v1/send/test123 -d '{}' | grep -q 'M_UNAUTHORIZED'" \
    "success"

# Test 8: Keys Claim without signature (should fail)
run_test "Keys Claim (no signature - should fail)" \
    "curl -s -X POST $SERVER_URL/_matrix/federation/v1/keys/claim -d '{}' | grep -q 'M_UNAUTHORIZED'" \
    "success"

echo -e "${BLUE}3. 测试端到端加密密钥API${NC}"
echo ""

# Test 9: Upload Keys (requires user authentication, not federation)
run_test "Upload Keys API" \
    "curl -s -X POST $SERVER_URL/_matrix/client/r0/keys/upload -H 'Content-Type: application/json' -d '{\"one_time_keys\":{}}' | grep -q 'errcode'" \
    "success"

# Test 10: Query Keys (requires user authentication)
run_test "Query Keys API" \
    "curl -s -X POST $SERVER_URL/_matrix/client/r0/keys/query -H 'Content-Type: application/json' -d '{\"device_keys\":{}}' | grep -q 'errcode'" \
    "success"

echo -e "${BLUE}4. 测试客户端API端点${NC}"
echo ""

# Test 11: Client Versions (public)
run_test "Client Versions API" \
    "curl -s $SERVER_URL/_matrix/client/versions | grep -q 'versions'" \
    "success"

# Test 12: Login (public)
run_test "Login API" \
    "curl -s -X POST $SERVER_URL/_matrix/client/r0/login -d '{\"type\":\"m.login.password\",\"user\":\"test\",\"password\":\"test\"}' | grep -q 'errcode'" \
    "success"

echo -e "${BLUE}================================${NC}"
echo -e "${BLUE}  测试结果汇总${NC}"
echo -e "${BLUE}================================${NC}"
echo ""
echo -e "总测试数: $TOTAL_TESTS"
echo -e "${GREEN}通过: $PASSED_TESTS${NC}"
echo -e "${RED}失败: $FAILED_TESTS${NC}"
echo ""

if [ $FAILED_TESTS -eq 0 ]; then
    echo -e "${GREEN}✓ 所有测试通过！${NC}"
    exit 0
else
    echo -e "${RED}✗ 部分测试失败${NC}"
    exit 1
fi
