//! GENERATED by `scripts/contract/gen_derived_routes.py` — DO NOT EDIT.
//!
//! Route manifest table derived from the real `.route(...)` surface (see the
//! extractor in `scripts/contract/extract_registered.py`). This replaces the
//! ~120 hand-copied `*_route_manifest()` helpers: instead of restating routes,
//! the compiler filters this table by `#[cfg]` and `derived_route_manifest`
//! filters it by the runtime [`ProfileFlags`] ceiling, then de-duplicates by
//! `(method, path)` keeping the highest rank.
//!
//! ## Row model
//!
//! * `RouteProfile` is a monotonic feature ceiling. `default` builds expose
//!   `Always`; `worker_enabled` adds `Worker`; `oidc_enabled` adds `Oidc`.
//!   `derived_route_manifest` keeps every row with `rank <= flags.rank()`.
//! * The two `/.well-known/{openid-configuration,jwks.json}` routes appear
//!   twice — once `Always` (label `oidc_fallback`) and once `Oidc`
//!   (label `oidc`, gated `#[cfg(feature = "builtin-oidc")]`). In the SDK
//!   lane both compile and the dedup keeps the higher-rank `oidc`; in the
//!   default lane the `Oidc` twin is cfg-stripped and `oidc_fallback` wins.
//!   That is exactly what the committed fixtures record.
//!
//! ## Regenerate
//!
//! ```text
//! python3 scripts/contract/gen_derived_routes.py
//! ```
//!
//! The generator refuses to emit unless this table reproduces all six fixtures
//! in `tests/unit/fixtures/{ledger_export,ledger_export_sdk}/` byte-equivalently
//! by `(method, path, registered_by)`, so editing it by hand is pointless — the
//! next regeneration overwrites it.
//!
//! ## Split structure
//!
//! The route table is split by `RouteProfile` into three `.inc.rs` files:
//! - `derived_route_table_always.inc.rs` — rows served in every profile
//! - `derived_route_table_worker.inc.rs` — rows gated on `worker_enabled`
//! - `derived_route_table_oidc.inc.rs`  — rows gated on `oidc_enabled`
//!
//! Each file defines `fn all_derived_*_rows()`. The aggregator
//! `all_derived_rows()` include!s all three.

#![allow(clippy::unreadable_literal)]

use super::route_ledger::RouteEntry;
use super::route_module::ProfileFlags;

/// Monotonic feature ceiling a row belongs to.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug)]
pub enum RouteProfile {
    /// Served in every profile.
    Always = 0,
    /// Served only when `worker_enabled`.
    Worker = 1,
    /// Served only when `oidc_enabled`.
    Oidc = 2,
}

/// A manifest row: the route plus the lowest profile that surfaces it.
pub struct DerivedRoute {
    /// The route entry itself.
    pub entry: RouteEntry,
    /// Minimum profile rank at which this row is live.
    pub rank: RouteProfile,
}

impl ProfileFlags {
    /// The feature ceiling for this flag combination, as a [`RouteProfile`].
    pub fn rank(&self) -> RouteProfile {
        if self.oidc_enabled {
            RouteProfile::Oidc
        } else if self.worker_enabled {
            RouteProfile::Worker
        } else {
            RouteProfile::Always
        }
    }
}

/// Project the live `AppState` flags onto the feature-ceiling rank.
pub fn rank_for_flags(flags: &ProfileFlags) -> RouteProfile {
    flags.rank()
}

// Per-profile route manifests — each includes its subset of routes.
include!("derived_route_table_always.inc.rs");
include!("derived_route_table_worker.inc.rs");
include!("derived_route_table_oidc.inc.rs");

/// Combined manifest that aggregates all profiles.
/// `derived_route_manifest` calls this to get the full list of rows.
fn all_derived_rows() -> Vec<DerivedRoute> {
    let mut rows: Vec<DerivedRoute> = Vec::with_capacity(1500);
    rows.extend(all_derived_always_rows());
    rows.extend(all_derived_worker_rows());
    rows.extend(all_derived_oidc_rows());
    rows
}

/// Profile-driven manifest. Keep rows at or below the flag ceiling, then
/// de-duplicate by `(method, path)` keeping the highest rank. Output is sorted
/// by `(path, method, registered_by)` for byte-stable diffs.
pub fn derived_route_manifest(flags: &ProfileFlags) -> Vec<RouteEntry> {
    let max_rank = rank_for_flags(flags);
    let mut best: std::collections::HashMap<(String, String), RouteProfile> =
        std::collections::HashMap::new();
    let mut kept: std::collections::HashMap<(String, String), RouteEntry> =
        std::collections::HashMap::new();
    for DerivedRoute { entry, rank } in all_derived_rows() {
        if rank > max_rank {
            continue;
        }
        let key = (entry.method.as_str().to_string(), entry.path.to_string());
        if let Some(prev) = best.get(&key) {
            if *prev >= rank {
                continue;
            }
        }
        best.insert(key.clone(), rank);
        kept.insert(key, entry);
    }
    let mut out: Vec<RouteEntry> = kept.into_values().collect();
    out.sort_by(|a, b| {
        a.path
            .cmp(b.path)
            .then_with(|| a.method.as_str().cmp(b.method.as_str()))
            .then_with(|| {
                a.registered_by.cmp(b.registered_by)
            })
    });
    out
}

#[cfg(test)]
mod derived_manifest_tests {
    use super::*;
    use crate::routes::ledger_export::LedgerArtifact;
    use crate::routes::route_module::ProfileFlags as PFlags;
    use std::collections::HashMap;

    fn parse_fixture(bytes: &[u8]) -> Vec<(String, String, String)> {
        let art: LedgerArtifact = serde_json::from_slice(bytes).unwrap();
        art.entries.into_iter().map(|e| (e.method, e.path, e.registered_by)).collect()
    }

    macro_rules! assert_derived_matches {
        ($profile:ident, $fixture:expr) => {
            let flags = match stringify!($profile) {
                "DEFAULT" => PFlags { oidc_enabled: false, worker_enabled: false, saml_enabled: false },
                "WORKER"  => PFlags { oidc_enabled: false, worker_enabled: true, saml_enabled: false },
                "ALL"     => PFlags { oidc_enabled: true, worker_enabled: true, saml_enabled: false },
                _ => unreachable!(),
            };
            let got = derived_route_manifest(&flags);
            let want = parse_fixture(include_bytes!($fixture));
            assert_eq!(got.len(), want.len(), "{} profile entry count mismatch", stringify!($profile));
            let mut got_map: HashMap<(String, String, String), ()> = HashMap::new();
            for e in &got {
                got_map.insert((e.method.as_str().to_string(), e.path.to_string(), e.registered_by.to_string()), ());
            }
            for (method, path, registered_by) in want {
                let key = (method.clone(), path.clone(), registered_by.clone());
                assert!(
                    got_map.contains_key(&key),
                    "{} profile missing row: {} {} {}",
                    stringify!($profile),
                    method,
                    path,
                    registered_by
                );
            }
        };
    }

    // Default build → ledger_export fixtures.
    #[cfg(not(any(
        feature = "all-extensions",
        feature = "voice-extended",
        feature = "saml-sso",
        feature = "cas-sso",
        feature = "voip-tracking",
        feature = "server-notifications",
        feature = "privacy-ext",
        feature = "builtin-oidc",
    )))]
    #[test]
    fn default_profile_matches_fixture() {
        assert_derived_matches!(
            DEFAULT,
            concat!(concat!(env!("CARGO_MANIFEST_DIR"), "/../tests/unit/fixtures"), "/ledger_export/default.json")
        );
    }

    #[cfg(not(any(
        feature = "all-extensions",
        feature = "voice-extended",
        feature = "saml-sso",
        feature = "cas-sso",
        feature = "voip-tracking",
        feature = "server-notifications",
        feature = "privacy-ext",
        feature = "builtin-oidc",
    )))]
    #[test]
    fn worker_profile_matches_fixture() {
        assert_derived_matches!(
            WORKER,
            concat!(concat!(env!("CARGO_MANIFEST_DIR"), "/../tests/unit/fixtures"), "/ledger_export/worker.json")
        );
    }

    #[cfg(not(any(
        feature = "all-extensions",
        feature = "voice-extended",
        feature = "saml-sso",
        feature = "cas-sso",
        feature = "voip-tracking",
        feature = "server-notifications",
        feature = "privacy-ext",
        feature = "builtin-oidc",
    )))]
    #[test]
    fn all_profile_matches_fixture() {
        assert_derived_matches!(
            ALL,
            concat!(concat!(env!("CARGO_MANIFEST_DIR"), "/../tests/unit/fixtures"), "/ledger_export/all.json")
        );
    }

    // SDK / all-extensions build → ledger_export_sdk fixtures.
    #[cfg(feature = "all-extensions")]
    #[test]
    fn sdk_default_profile_matches_fixture() {
        assert_derived_matches!(
            DEFAULT,
            concat!(concat!(env!("CARGO_MANIFEST_DIR"), "/../tests/unit/fixtures"), "/ledger_export_sdk/default.json")
        );
    }

    #[cfg(feature = "all-extensions")]
    #[test]
    fn sdk_worker_profile_matches_fixture() {
        assert_derived_matches!(
            WORKER,
            concat!(concat!(env!("CARGO_MANIFEST_DIR"), "/../tests/unit/fixtures"), "/ledger_export_sdk/worker.json")
        );
    }

    #[cfg(feature = "all-extensions")]
    #[test]
    fn sdk_all_profile_matches_fixture() {
        assert_derived_matches!(
            ALL,
            concat!(concat!(env!("CARGO_MANIFEST_DIR"), "/../tests/unit/fixtures"), "/ledger_export_sdk/all.json")
        );
    }
}
